/* ════════════════════════════════════════════════════════════
   ALALAAM — figure design-system data model
   Every figure carries the same ten properties:
     teacher · student · peer · bornCity · diedCity · livedCity
     · acquaintances · sameGeneration · biography · publications
   Bilingual: each value is {en, ar}; people may carry an id for
   click-through to that figure's own card.
   Dates approximate; "—" / "None recorded" is used honestly where
   the historical record is silent.
   ════════════════════════════════════════════════════════════ */
(function () {
  const P = (en, ar, id) => (id ? { en, ar, id } : { en, ar });
  const C = (en, ar) => ({ en, ar });
  const B = (en, ar) => ({ en, ar });
  const W = (en, ar, y) => ({ en, ar, y: y || "" });

  const F = {};

  F.kw = {
    glyph: "خ", cat: "self",
    name: C("al-Khwarizmi", "الخوارزمي"),
    full: C("Muhammad ibn Musa al-Khwarizmi", "محمد بن موسى الخوارزمي"),
    life: C("c. 780 – c. 850", "نحو ٧٨٠ – ٨٥٠"),
    role: C("Mathematician · Astronomer · Geographer", "رياضياتي · فلكي · جغرافي"),
    born: C("Khwarazm", "خوارزم"),
    died: C("Baghdad", "بغداد"),
    lived: [C("Baghdad", "بغداد")],
    teacher: [P("Inherited from books — Brahmagupta", "ورث عن الكتب — براهماغوبتا", "brahmagupta"), P("Ptolemy", "بطليموس", "ptolemy"), P("Euclid", "إقليدس", "euclid")],
    student: [P("None recorded by name", "لا أحد مذكور بالاسم")],
    peer: [P("The Banu Musa", "بنو موسى", "banumusa"), P("al-Kindi", "الكِندي", "kindi"), P("al-Farghani", "الفَرغاني", "farghani"), P("Hunayn ibn Ishaq", "حنين بن إسحاق", "hunayn"), P("Sind ibn Ali", "سند بن علي", "sind")],
    acq: [P("Caliph al-Ma'mun", "الخليفة المأمون", "mamun"), P("Caliph al-Mu'tasim", "الخليفة المعتصم", "mutasim")],
    gen: [P("Abu Nuwas", "أبو نوّاس", "abunuwas"), P("al-Shafi'i", "الإمام الشافعي", "shafii"), P("Ibn Hanbal", "ابن حنبل", "hanbal"), P("al-Jahiz", "الجاحظ", "jahiz"), P("Charlemagne", "شارلمان", "charlemagne")],
    bio: B("A founding scholar of the Abbasid House of Wisdom under al-Ma'mun. His method of balancing equations named algebra, and the Latin of his name became the word 'algorithm'.",
           "من مؤسِّسي علماء بيت الحكمة العباسي في كنف المأمون. منهجُه في موازنة المعادلات أعطى «الجبر» اسمَه، ومن صورة اسمه باللاتينية جاءت كلمة «خوارزمية»."),
    pubs: [W("Al-Jabr wa'l-Muqabala", "الجبر والمقابلة", "c.820"), W("On Calculation with Hindu Numerals", "في حساب الهند", "c.825"), W("Zij al-Sindhind", "زيج السند هند", "c.820s"), W("Kitab Surat al-Ard", "كتاب صورة الأرض", "c.833"), W("On the Astrolabe", "في العمل بالأسطرلاب", "")],
  };

  F.brahmagupta = {
    glyph: "ब", cat: "influence",
    name: C("Brahmagupta", "براهماغوبتا"),
    full: C("Brahmagupta", "براهماغوبتا"),
    life: C("598 – 668", "٥٩٨ – ٦٦٨"),
    role: C("Mathematician · Astronomer", "رياضياتي · فلكي"),
    born: C("Bhinmal", "بهينمال"),
    died: C("Ujjain", "أُجَّين"),
    lived: [C("Ujjain", "أُجَّين")],
    teacher: [P("Unknown", "غير معروف")],
    student: [P("Through books — al-Khwarizmi", "عبر الكتب — الخوارزمي", "kw")],
    peer: [P("The astronomers of Ujjain", "فلكيّو أُجَّين")],
    acq: [P("—", "—")],
    gen: [P("—", "—")],
    bio: B("Head of the Ujjain observatory whose Brahmasphutasiddhanta carried the decimal numerals and the first rules for zero that al-Khwarizmi later systematised.",
           "رئيس مرصد أُجَّين، حمل كتابُه «براهما سفوتا سدهانتا» الأرقامَ العشرية وأوّل قواعد الصفر التي نظّمها الخوارزمي لاحقًا."),
    pubs: [W("Brahmasphutasiddhanta", "براهما سفوتا سدهانتا", "628"), W("Khandakhadyaka", "خانداخاديكا", "665")],
  };

  F.ptolemy = {
    glyph: "Π", cat: "influence",
    name: C("Ptolemy", "بطليموس"),
    full: C("Claudius Ptolemy", "كلوديوس بطليموس"),
    life: C("c. 100 – 170", "نحو ١٠٠ – ١٧٠"),
    role: C("Astronomer · Geographer", "فلكي · جغرافي"),
    born: C("Egypt", "مصر"),
    died: C("Alexandria", "الإسكندرية"),
    lived: [C("Alexandria", "الإسكندرية")],
    teacher: [P("The Alexandrian tradition", "تقليد الإسكندرية")],
    student: [P("Through books — al-Khwarizmi", "عبر الكتب — الخوارزمي", "kw"), P("al-Farghani", "الفَرغاني", "farghani")],
    peer: [P("—", "—")],
    acq: [P("—", "—")],
    gen: [P("—", "—")],
    bio: B("The astronomer of Alexandria whose Almagest and Geography framed the heavens and the earth for a thousand years — and set the targets al-Khwarizmi would correct.",
           "فلكيُّ الإسكندرية الذي وضع كتاباه «المجسطي» و«الجغرافيا» إطارَ السماء والأرض ألف عام — وحدّدا ما سيصحّحه الخوارزمي."),
    pubs: [W("Almagest", "المجسطي", "c.150"), W("Geography", "الجغرافيا", ""), W("Tetrabiblos", "الأربعة مقالات", "")],
  };

  F.diophantus = {
    glyph: "Δ", cat: "influence",
    name: C("Diophantus", "ديوفانتوس"),
    full: C("Diophantus of Alexandria", "ديوفانتوس الإسكندري"),
    life: C("c. 201 – 285", "نحو ٢٠١ – ٢٨٥"),
    role: C("Mathematician", "رياضياتي"),
    born: C("Alexandria", "الإسكندرية"),
    died: C("Alexandria", "الإسكندرية"),
    lived: [C("Alexandria", "الإسكندرية")],
    teacher: [P("Unknown", "غير معروف")],
    student: [P("Through books — later algebraists", "عبر الكتب — الجبريّون اللاحقون")],
    peer: [P("—", "—")],
    acq: [P("—", "—")],
    gen: [P("—", "—")],
    bio: B("The Greek 'father of arithmetic', whose Arithmetica treated equations with unknowns and prefigured the problems al-Khwarizmi would make general.",
           "«أبو الحساب» اليوناني، عالج كتابُه «الحساب» المعادلاتِ بالمجاهيل ومهّد للمسائل التي عمّمها الخوارزمي."),
    pubs: [W("Arithmetica", "الحساب (أريثمتيكا)", "")],
  };

  F.euclid = {
    glyph: "Ε", cat: "influence",
    name: C("Euclid", "إقليدس"),
    full: C("Euclid of Alexandria", "إقليدس الإسكندري"),
    life: C("c. 325 – 265 BCE", "نحو ٣٢٥ – ٢٦٥ ق.م"),
    role: C("Mathematician", "رياضياتي"),
    born: C("Unknown", "غير معروف"),
    died: C("Alexandria", "الإسكندرية"),
    lived: [C("Alexandria", "الإسكندرية")],
    teacher: [P("The school of Plato", "مدرسة أفلاطون")],
    student: [P("Through books — all geometers since", "عبر الكتب — كل الهندسيين بعده")],
    peer: [P("—", "—")],
    acq: [P("—", "—")],
    gen: [P("—", "—")],
    bio: B("Author of the Elements, the foundation of geometry. Its proofs gave al-Khwarizmi the rigorous ground on which he justified completing the square.",
           "مؤلّف «الأصول»، أساس الهندسة. منحت براهينُه الخوارزميَّ الأرضَ الصارمة التي برهن عليها قاعدة إكمال المربّع."),
    pubs: [W("Elements", "الأصول", ""), W("Optics", "المناظر", ""), W("Data", "المعطيات", "")],
  };

  F.harun = {
    glyph: "ه", cat: "patron",
    name: C("Harun al-Rashid", "هارون الرشيد"),
    full: C("Harun al-Rashid", "هارون الرشيد"),
    life: C("763 – 809", "٧٦٣ – ٨٠٩"),
    role: C("Caliph · Patron", "خليفة · راعٍ"),
    born: C("Rayy", "الرَّي"),
    died: C("Tus", "طوس"),
    lived: [C("Baghdad", "بغداد")],
    teacher: [P("Yahya the Barmakid", "يحيى البرمكي")],
    student: [P("—", "—")],
    peer: [P("—", "—")],
    acq: [P("al-Shafi'i", "الإمام الشافعي", "shafii"), P("Abu Nuwas", "أبو نوّاس", "abunuwas")],
    gen: [P("Charlemagne", "شارلمان", "charlemagne"), P("Abu Nuwas", "أبو نوّاس", "abunuwas")],
    bio: B("Under his caliphate Baghdad became the richest city of the age and the translation movement took root — the world into which al-Khwarizmi came.",
           "في خلافته صارت بغداد أغنى مدن العصر وترسّخت حركة الترجمة — العالم الذي قَدِم إليه الخوارزمي."),
    pubs: [W("Patron — early House of Wisdom", "راعٍ — بدايات بيت الحكمة", "")],
  };

  F.mamun = {
    glyph: "م", cat: "patron",
    name: C("al-Ma'mun", "المأمون"),
    full: C("Caliph al-Ma'mun", "الخليفة المأمون"),
    life: C("786 – 833", "٧٨٦ – ٨٣٣"),
    role: C("Caliph · Patron of the House of Wisdom", "خليفة · راعي بيت الحكمة"),
    born: C("Baghdad", "بغداد"),
    died: C("Tarsus", "طرسوس"),
    lived: [C("Merv", "مرو"), C("Baghdad", "بغداد")],
    teacher: [P("—", "—")],
    student: [P("—", "—")],
    peer: [P("—", "—")],
    acq: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("The Banu Musa", "بنو موسى", "banumusa"), P("al-Kindi", "الكِندي", "kindi")],
    gen: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("al-Jahiz", "الجاحظ", "jahiz")],
    bio: B("Al-Khwarizmi's direct patron. He championed the House of Wisdom and commissioned its great astronomical and geographic projects.",
           "راعي الخوارزمي المباشر. احتضن بيت الحكمة وكلّف بمشاريعه الفلكية والجغرافية الكبرى."),
    pubs: [W("Commissioned the Zij & the world map", "كلّف بالزيج وخريطة العالم", ""), W("The meridian measurement", "قياس خط الزوال", "")],
  };

  F.mutasim = {
    glyph: "م", cat: "patron",
    name: C("al-Mu'tasim", "المعتصم"),
    full: C("Caliph al-Mu'tasim", "الخليفة المعتصم"),
    life: C("794 – 842", "٧٩٤ – ٨٤٢"),
    role: C("Caliph · Patron", "خليفة · راعٍ"),
    born: C("Baghdad", "بغداد"),
    died: C("Samarra", "سامراء"),
    lived: [C("Baghdad", "بغداد"), C("Samarra", "سامراء")],
    teacher: [P("—", "—")],
    student: [P("—", "—")],
    peer: [P("—", "—")],
    acq: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("al-Kindi", "الكِندي", "kindi")],
    gen: [P("al-Kindi", "الكِندي", "kindi")],
    bio: B("Successor to al-Ma'mun who founded Samarra and sustained the scholars of the House of Wisdom into the next generation.",
           "خليفة المأمون، أسّس سامراء وأدام رعاية علماء بيت الحكمة إلى الجيل التالي."),
    pubs: [W("Founded Samarra", "أسّس سامراء", "836"), W("Sustained the House of Wisdom", "أدام بيت الحكمة", "")],
  };

  F.banumusa = {
    glyph: "ب", cat: "peer",
    name: C("The Banu Musa", "بنو موسى"),
    full: C("Banu Musa ibn Shakir", "بنو موسى بن شاكر"),
    life: C("fl. 9th c.", "ازدهروا ق ٩"),
    role: C("Engineers · Mathematicians · Patrons", "مهندسون · رياضياتيون · رعاة"),
    born: C("Baghdad", "بغداد"),
    died: C("Baghdad", "بغداد"),
    lived: [C("Baghdad", "بغداد")],
    teacher: [P("Under al-Ma'mun", "في كنف المأمون", "mamun")],
    student: [P("Thabit ibn Qurra", "ثابت بن قُرّة"), P("Hunayn ibn Ishaq", "حنين بن إسحاق", "hunayn")],
    peer: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("al-Kindi", "الكِندي", "kindi")],
    acq: [P("Caliph al-Ma'mun", "الخليفة المأمون", "mamun")],
    gen: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("al-Kindi", "الكِندي", "kindi")],
    bio: B("Three brothers — Muhammad, Ahmad and al-Hasan — patrons, engineers and mathematicians whose Book of Ingenious Devices shared al-Khwarizmi's circle.",
           "ثلاثة إخوة — محمد وأحمد والحسن — رعاة ومهندسون ورياضياتيون شارك كتابُهم «الحِيَل» حلقةَ الخوارزمي."),
    pubs: [W("Book of Ingenious Devices", "كتاب الحِيَل", "850"), W("On the Measurement of Plane & Spherical Figures", "في مساحة الأشكال", "")],
  };

  F.kindi = {
    glyph: "ك", cat: "peer",
    name: C("al-Kindi", "الكِندي"),
    full: C("Abu Yusuf al-Kindi", "أبو يوسف الكِندي"),
    life: C("c. 801 – 873", "نحو ٨٠١ – ٨٧٣"),
    role: C("Philosopher · Polymath", "فيلسوف · موسوعي"),
    born: C("Kufa", "الكوفة"),
    died: C("Baghdad", "بغداد"),
    lived: [C("Basra", "البصرة"), C("Baghdad", "بغداد")],
    teacher: [P("Educated in Basra & Baghdad", "تعلّم في البصرة وبغداد")],
    student: [P("al-Sarakhsi", "السرخسي")],
    peer: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("The Banu Musa", "بنو موسى", "banumusa"), P("Hunayn ibn Ishaq", "حنين بن إسحاق", "hunayn")],
    acq: [P("Caliph al-Ma'mun", "الخليفة المأمون", "mamun"), P("Caliph al-Mu'tasim", "الخليفة المعتصم", "mutasim")],
    gen: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("al-Jahiz", "الجاحظ", "jahiz")],
    bio: B("The 'Philosopher of the Arabs' — polymath of philosophy, optics and medicine, and author of the first known work on breaking ciphers.",
           "«فيلسوف العرب» — موسوعيٌّ في الفلسفة والبصريات والطب، ومؤلّف أوّل عملٍ معروف في كسر الشيفرات."),
    pubs: [W("On First Philosophy", "في الفلسفة الأولى", ""), W("On Deciphering Cryptographic Messages", "في استخراج المعمّى", ""), W("On the Use of Indian Numerals", "في استعمال الأعداد الهندية", "")],
  };

  F.hunayn = {
    glyph: "ح", cat: "peer",
    name: C("Hunayn ibn Ishaq", "حنين بن إسحاق"),
    full: C("Hunayn ibn Ishaq al-Ibadi", "حنين بن إسحاق العبادي"),
    life: C("809 – 873", "٨٠٩ – ٨٧٣"),
    role: C("Physician · Master translator", "طبيب · سيّد المترجمين"),
    born: C("al-Hira", "الحيرة"),
    died: C("Baghdad", "بغداد"),
    lived: [C("Baghdad", "بغداد")],
    teacher: [P("Ibn Masawayh", "ابن ماسويه")],
    student: [P("Hubaysh", "حُبَيش"), P("Isa ibn Yahya", "عيسى بن يحيى")],
    peer: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("The Banu Musa", "بنو موسى", "banumusa"), P("al-Kindi", "الكِندي", "kindi")],
    acq: [P("The Banu Musa", "بنو موسى", "banumusa")],
    gen: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("al-Jahiz", "الجاحظ", "jahiz")],
    bio: B("The master translator of the age, rendering Greek medicine and science into Arabic with unmatched care for the House of Wisdom.",
           "سيّد المترجمين في عصره، نقل الطب والعلم اليوناني إلى العربية بعناية لا تُضاهى لبيت الحكمة."),
    pubs: [W("Ten Treatises on the Eye", "العشر مقالات في العين", ""), W("Translations of Galen & Hippocrates", "ترجمات جالينوس وأبقراط", "")],
  };

  F.farghani = {
    glyph: "ف", cat: "peer",
    name: C("al-Farghani", "الفَرغاني"),
    full: C("Ahmad ibn Muhammad al-Farghani", "أحمد بن محمد الفَرغاني"),
    life: C("c. 800 – 870", "نحو ٨٠٠ – ٨٧٠"),
    role: C("Astronomer", "فلكي"),
    born: C("Farghana", "فَرغانة"),
    died: C("Cairo", "القاهرة"),
    lived: [C("Baghdad", "بغداد"), C("Cairo", "القاهرة")],
    teacher: [P("Through books — Ptolemy", "عبر الكتب — بطليموس", "ptolemy")],
    student: [P("Through books — European astronomers", "عبر الكتب — فلكيّو أوروبا")],
    peer: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("The Banu Musa", "بنو موسى", "banumusa")],
    acq: [P("Caliph al-Ma'mun", "الخليفة المأمون", "mamun")],
    gen: [P("al-Khwarizmi", "الخوارزمي", "kw")],
    bio: B("Astronomer — the Latin 'Alfraganus' — whose summary of Ptolemy shaped European cosmology for centuries and was quoted by Dante.",
           "فلكيٌّ — «ألفراغانوس» باللاتينية — صاغ خلاصةً لبطليموس شكّلت علم الكون الأوروبي قرونًا واقتبسها دانتي."),
    pubs: [W("Elements of Astronomy", "جوامع علم النجوم", "c.833")],
  };

  F.sind = {
    glyph: "س", cat: "peer",
    name: C("Sind ibn Ali", "سند بن علي"),
    full: C("Sind ibn Ali", "سند بن علي"),
    life: C("fl. 9th c.", "ازدهر ق ٩"),
    role: C("Astronomer · Mathematician", "فلكي · رياضياتي"),
    born: C("Unknown", "غير معروف"),
    died: C("Baghdad", "بغداد"),
    lived: [C("Baghdad", "بغداد")],
    teacher: [P("The House of Wisdom", "بيت الحكمة")],
    student: [P("—", "—")],
    peer: [P("al-Khwarizmi", "الخوارزمي", "kw")],
    acq: [P("Caliph al-Ma'mun", "الخليفة المأمون", "mamun")],
    gen: [P("al-Khwarizmi", "الخوارزمي", "kw")],
    bio: B("Astronomer of the House of Wisdom and a collaborator on the observational programme behind the Zij and the meridian measurement.",
           "فلكيُّ بيت الحكمة وشريكٌ في برنامج الرصد وراء «الزيج» وقياس خط الزوال."),
    pubs: [W("Astronomical tables", "جداول فلكية", ""), W("Contributions to the Zij", "إسهامات في الزيج", "")],
  };

  F.abukamil = {
    glyph: "أ", cat: "successor",
    name: C("Abu Kamil", "أبو كامل"),
    full: C("Abu Kamil Shuja ibn Aslam", "أبو كامل شجاع بن أسلم"),
    life: C("c. 850 – 930", "نحو ٨٥٠ – ٩٣٠"),
    role: C("Mathematician", "رياضياتي"),
    born: C("Egypt", "مصر"),
    died: C("Egypt", "مصر"),
    lived: [C("Egypt", "مصر")],
    teacher: [P("Through books — al-Khwarizmi", "عبر الكتب — الخوارزمي", "kw")],
    student: [P("Through books — Fibonacci", "عبر الكتب — فيبوناتشي", "fibonacci"), P("al-Karaji", "الكَرَجي", "karaji")],
    peer: [P("—", "—")],
    acq: [P("—", "—")],
    gen: [P("al-Battani", "البتّاني", "battani")],
    bio: B("'The Egyptian reckoner' — the first to build directly on Al-Jabr, extending algebra to higher powers and irrational solutions.",
           "«الحاسب المصري» — أوّل من بنى مباشرةً على «الجبر»، فامتدّ به إلى القوى الأعلى والحلول الصمّاء."),
    pubs: [W("Book of Algebra", "كتاب في الجبر والمقابلة", ""), W("Book of Rare Things in Calculation", "كتاب الطرائف في الحساب", "")],
  };

  F.battani = {
    glyph: "ب", cat: "successor",
    name: C("al-Battani", "البتّاني"),
    full: C("Muhammad ibn Jabir al-Battani", "محمد بن جابر البتّاني"),
    life: C("c. 858 – 929", "نحو ٨٥٨ – ٩٢٩"),
    role: C("Astronomer · Mathematician", "فلكي · رياضياتي"),
    born: C("Harran", "حرّان"),
    died: C("Samarra", "سامراء"),
    lived: [C("Raqqa", "الرقّة")],
    teacher: [P("Through books — Ptolemy", "عبر الكتب — بطليموس", "ptolemy")],
    student: [P("Through books — Copernicus, Kepler", "عبر الكتب — كوبرنيكوس، كبلر")],
    peer: [P("Thabit ibn Qurra", "ثابت بن قُرّة")],
    acq: [P("—", "—")],
    gen: [P("Abu Kamil", "أبو كامل", "abukamil")],
    bio: B("Astronomer — the Latin 'Albategnius' — who refined Ptolemy's tables and the trigonometry al-Khwarizmi had begun, measuring the solar year with great precision.",
           "فلكيٌّ — «ألبتانيوس» باللاتينية — نقّح جداول بطليموس وعلمَ المثلثات الذي بدأه الخوارزمي، وقاس السنة الشمسية بدقّة بالغة."),
    pubs: [W("Kitab az-Zij (De Motu Stellarum)", "كتاب الزيج الصابئ", "")],
  };

  F.karaji = {
    glyph: "ك", cat: "successor",
    name: C("al-Karaji", "الكَرَجي"),
    full: C("Abu Bakr al-Karaji", "أبو بكر الكَرَجي"),
    life: C("953 – 1029", "٩٥٣ – ١٠٢٩"),
    role: C("Mathematician · Engineer", "رياضياتي · مهندس"),
    born: C("Karaj", "كَرَج"),
    died: C("Baghdad", "بغداد"),
    lived: [C("Baghdad", "بغداد")],
    teacher: [P("Through books — al-Khwarizmi", "عبر الكتب — الخوارزمي", "kw"), P("Abu Kamil", "أبو كامل", "abukamil")],
    student: [P("Through books — al-Samawal", "عبر الكتب — السموأل")],
    peer: [P("—", "—")],
    acq: [P("—", "—")],
    gen: [P("Ibn Sina (era)", "ابن سينا (العصر)")],
    bio: B("Freed algebra from geometry, treating the unknown as a thing in itself — a direct descendant of Al-Jabr and a step toward modern algebra.",
           "حرّر الجبر من الهندسة، فعامل المجهولَ شيئًا قائمًا بذاته — وريثٌ مباشر لـ«الجبر» وخطوةٌ نحو الجبر الحديث."),
    pubs: [W("al-Fakhri", "الفخري", ""), W("al-Badi", "البديع", ""), W("al-Kafi fi al-Hisab", "الكافي في الحساب", "")],
  };

  F.khayyam = {
    glyph: "ع", cat: "successor",
    name: C("Omar Khayyam", "عمر الخيّام"),
    full: C("Ghiyath al-Din Omar Khayyam", "غياث الدين عمر الخيّام"),
    life: C("1048 – 1131", "١٠٤٨ – ١١٣١"),
    role: C("Mathematician · Astronomer · Poet", "رياضياتي · فلكي · شاعر"),
    born: C("Nishapur", "نيسابور"),
    died: C("Nishapur", "نيسابور"),
    lived: [C("Samarkand", "سمرقند"), C("Isfahan", "أصفهان"), C("Nishapur", "نيسابور")],
    teacher: [P("Through books — al-Khwarizmi", "عبر الكتب — الخوارزمي", "kw")],
    student: [P("Through books — later algebraists", "عبر الكتب — الجبريّون اللاحقون")],
    peer: [P("al-Khazini", "الخازني")],
    acq: [P("Nizam al-Mulk (patron)", "نظام الملك (الراعي)"), P("Malik-Shah", "ملكشاه")],
    gen: [P("al-Ghazali", "الغزالي")],
    bio: B("Poet and mathematician who classified and solved the cubic equations beyond al-Khwarizmi's reach, and reformed the calendar with great accuracy.",
           "شاعرٌ ورياضياتي صنّف المعادلات التكعيبية وحلّها فيما تجاوز مدى الخوارزمي، وأصلح التقويم بدقّة عالية."),
    pubs: [W("Treatise on Problems of Algebra", "رسالة في البراهين على مسائل الجبر", ""), W("Rubaiyat", "الرباعيات", ""), W("Jalali calendar reform", "إصلاح التقويم الجلالي", "1079")],
  };

  F.fibonacci = {
    glyph: "L", cat: "successor",
    name: C("Fibonacci", "فيبوناتشي"),
    full: C("Leonardo of Pisa", "ليوناردو البيزي"),
    life: C("c. 1170 – 1250", "نحو ١١٧٠ – ١٢٥٠"),
    role: C("Mathematician", "رياضياتي"),
    born: C("Pisa", "بيزا"),
    died: C("Pisa", "بيزا"),
    lived: [C("Bugia", "بجاية"), C("Pisa", "بيزا")],
    teacher: [P("Through books — al-Khwarizmi", "عبر الكتب — الخوارزمي", "kw"), P("Abu Kamil", "أبو كامل", "abukamil")],
    student: [P("Europe's reckoning masters", "أساتذة الحساب في أوروبا")],
    peer: [P("—", "—")],
    acq: [P("Frederick II's court", "بلاط فريدريك الثاني")],
    gen: [P("—", "—")],
    bio: B("Leonardo of Pisa, who learned Hindu-Arabic numerals from Arab merchants in Bugia and carried al-Khwarizmi's reckoning into Europe in his Liber Abaci.",
           "ليوناردو البيزي، تعلّم الأرقامَ الهندية-العربية من تجّار العرب في بجاية، وحمل حسابَ الخوارزمي إلى أوروبا في «كتاب الحساب»."),
    pubs: [W("Liber Abaci", "كتاب الحساب (ليبر أباتشي)", "1202"), W("Practica Geometriae", "الهندسة العملية", "1220"), W("Liber Quadratorum", "كتاب المربّعات", "1225")],
  };

  F.shafii = {
    glyph: "ش", cat: "world",
    name: C("al-Shafi'i", "الشافعي"),
    full: C("Imam Muhammad al-Shafi'i", "الإمام محمد الشافعي"),
    life: C("767 – 820", "٧٦٧ – ٨٢٠"),
    role: C("Jurist · Founder of a school of law", "فقيه · مؤسّس مذهب"),
    born: C("Gaza", "غزّة"),
    died: C("Cairo", "القاهرة"),
    lived: [C("Mecca", "مكّة"), C("Baghdad", "بغداد"), C("Cairo", "القاهرة")],
    teacher: [P("Malik ibn Anas", "مالك بن أنس")],
    student: [P("Ahmad ibn Hanbal", "أحمد بن حنبل", "hanbal")],
    peer: [P("The jurists of Baghdad", "فقهاء بغداد")],
    acq: [P("Harun al-Rashid's court", "بلاط هارون الرشيد", "harun")],
    gen: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("Ibn Hanbal", "ابن حنبل", "hanbal")],
    bio: B("Jurist who founded one of the great schools of Islamic law in the same decades and the same city as al-Khwarizmi's rise.",
           "فقيهٌ أسّس أحد المذاهب الكبرى في الفقه الإسلامي في العقود ذاتها والمدينة ذاتها لصعود الخوارزمي."),
    pubs: [W("al-Risala", "الرسالة", ""), W("Kitab al-Umm", "كتاب الأم", "")],
  };

  F.hanbal = {
    glyph: "ح", cat: "world",
    name: C("Ibn Hanbal", "ابن حنبل"),
    full: C("Ahmad ibn Hanbal", "أحمد بن حنبل"),
    life: C("780 – 855", "٧٨٠ – ٨٥٥"),
    role: C("Theologian · Jurist · Traditionist", "محدِّث · فقيه"),
    born: C("Baghdad", "بغداد"),
    died: C("Baghdad", "بغداد"),
    lived: [C("Baghdad", "بغداد")],
    teacher: [P("al-Shafi'i", "الشافعي", "shafii")],
    student: [P("al-Bukhari (circle)", "البخاري (الحلقة)")],
    peer: [P("The traditionists of Baghdad", "محدِّثو بغداد")],
    acq: [P("Caliph al-Mu'tasim", "الخليفة المعتصم", "mutasim")],
    gen: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("al-Shafi'i", "الشافعي", "shafii")],
    bio: B("Theologian and jurist, born — by tradition — the same year as al-Khwarizmi and into the same Baghdad; founder of the Hanbali school.",
           "محدِّثٌ وفقيه، وُلد بحسب الرواية عام الخوارزمي نفسه وفي بغداد ذاتها؛ مؤسّس المذهب الحنبلي."),
    pubs: [W("Musnad", "المسند", "")],
  };

  F.abunuwas = {
    glyph: "ن", cat: "world",
    name: C("Abu Nuwas", "أبو نوّاس"),
    full: C("Abu Nuwas al-Hasan ibn Hani", "أبو نوّاس الحسن بن هانئ"),
    life: C("756 – 814", "٧٥٦ – ٨١٤"),
    role: C("Poet", "شاعر"),
    born: C("Ahvaz", "الأهواز"),
    died: C("Baghdad", "بغداد"),
    lived: [C("Basra", "البصرة"), C("Kufa", "الكوفة"), C("Baghdad", "بغداد")],
    teacher: [P("Khalaf al-Ahmar", "خلف الأحمر")],
    student: [P("The Abbasid poets", "شعراء العباسيين")],
    peer: [P("The court poets", "شعراء البلاط")],
    acq: [P("Harun al-Rashid", "هارون الرشيد", "harun")],
    gen: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("Harun al-Rashid", "هارون الرشيد", "harun")],
    bio: B("The great wine-and-wit poet of the Abbasid court — the literary voice of al-Khwarizmi's Baghdad.",
           "شاعر الخمر والظرف الأكبر في البلاط العباسي — الصوت الأدبي لبغداد الخوارزمي."),
    pubs: [W("Diwan of Abu Nuwas", "ديوان أبي نوّاس", "")],
  };

  F.jahiz = {
    glyph: "ج", cat: "world",
    name: C("al-Jahiz", "الجاحظ"),
    full: C("Amr ibn Bahr al-Jahiz", "عمرو بن بحر الجاحظ"),
    life: C("776 – 868", "٧٧٦ – ٨٦٨"),
    role: C("Prose master · Polymath", "إمام النثر · موسوعي"),
    born: C("Basra", "البصرة"),
    died: C("Basra", "البصرة"),
    lived: [C("Basra", "البصرة"), C("Baghdad", "بغداد")],
    teacher: [P("The scholars of Basra", "علماء البصرة")],
    student: [P("The Arabic prose tradition", "تقليد النثر العربي")],
    peer: [P("al-Kindi", "الكِندي", "kindi")],
    acq: [P("The Abbasid court", "البلاط العباسي")],
    gen: [P("al-Khwarizmi", "الخوارزمي", "kw"), P("al-Kindi", "الكِندي", "kindi")],
    bio: B("Prose master whose Book of Animals shows the same encyclopaedic appetite for the world that drove the House of Wisdom.",
           "إمام النثر، يُظهر «كتاب الحيوان» النهمَ الموسوعي ذاته للعالم الذي حرّك بيت الحكمة."),
    pubs: [W("Kitab al-Hayawan (Book of Animals)", "كتاب الحيوان", ""), W("al-Bayan wa al-Tabyin", "البيان والتبيين", ""), W("Book of Misers", "كتاب البخلاء", "")],
  };

  F.charlemagne = {
    glyph: "C", cat: "world",
    name: C("Charlemagne", "شارلمان"),
    full: C("Charlemagne, Emperor of the West", "شارلمان، إمبراطور الغرب"),
    life: C("748 – 814", "٧٤٨ – ٨١٤"),
    role: C("Emperor · Patron of learning", "إمبراطور · راعي العلم"),
    born: C("Frankish lands", "بلاد الفرنجة"),
    died: C("Aachen", "آخن"),
    lived: [C("Aachen", "آخن")],
    teacher: [P("Alcuin of York", "ألكوين اليوركي")],
    student: [P("The Carolingian schools", "المدارس الكارولنجية")],
    peer: [P("—", "—")],
    acq: [P("Harun al-Rashid (embassies)", "هارون الرشيد (سفارات)", "harun")],
    gen: [P("Harun al-Rashid", "هارون الرشيد", "harun")],
    bio: B("Crowned emperor in the West in the same generation; his Carolingian revival of letters a distant mirror of Baghdad's golden age.",
           "تُوِّج إمبراطورًا في الغرب في الجيل نفسه؛ ونهضتُه الكارولنجية في العلم مرآةٌ بعيدة لعصر بغداد الذهبي."),
    pubs: [W("Patron — the Carolingian Renaissance", "راعٍ — النهضة الكارولنجية", "")],
  };

  F.ziryab = {
    glyph: "ز", cat: "world",
    name: C("Ziryab", "زرياب"),
    full: C("Abu al-Hasan Ali ibn Nafi (Ziryab)", "أبو الحسن علي بن نافع (زرياب)"),
    life: C("789 – 857", "٧٨٩ – ٨٥٧"),
    role: C("Musician · Polymath", "موسيقي · موسوعي"),
    born: C("Baghdad", "بغداد"),
    died: C("Cordoba", "قرطبة"),
    lived: [C("Baghdad", "بغداد"), C("Cordoba", "قرطبة")],
    teacher: [P("Ishaq al-Mawsili", "إسحاق الموصلي")],
    student: [P("The Andalusian music school", "مدرسة الموسيقى الأندلسية")],
    peer: [P("The court musicians", "موسيقيّو البلاط")],
    acq: [P("Abd al-Rahman II", "عبد الرحمن الثاني")],
    gen: [P("al-Khwarizmi", "الخوارزمي", "kw")],
    bio: B("Musician and polymath who carried Baghdad's refinements — music, cuisine, fashion — clear across the world to al-Andalus.",
           "موسيقيٌّ وموسوعيٌّ حمل رقيّ بغداد — موسيقى ومطبخًا وأزياء — عبر العالم إلى الأندلس."),
    pubs: [W("Founded the Cordoba music school", "أسّس مدرسة الموسيقى بقرطبة", ""), W("Added the fifth string to the oud", "أضاف الوتر الخامس للعود", "")],
  };

  window.FIG = F;
  window.FIG_ORDER = ["kw","mamun","mutasim","harun","banumusa","kindi","hunayn","farghani","sind","brahmagupta","ptolemy","diophantus","euclid","abukamil","battani","karaji","khayyam","fibonacci","shafii","hanbal","abunuwas","jahiz","charlemagne","ziryab"];
})();
